EPMDJ-6858: Implement installation page
Drill4J/drill4j.github.io pull request #21
Opened 2021-04-08 14:27 UTC by IliaSolovev

Issue: EPMDJ-6858

2021-04-08 15:50 UTC, RomanDavlyatshin requested changes

2021-04-08 15:50 UTC, RomanDavlyatshin commented on src/theme/MDXPage/banner.tsx
> +export const Banner = ({ backgroundSrc, children, ...rest }: Props) => (
Why placing `<Banner>` in the `/theme/MDXPage`? We could use it anywhere (including non-mdx pages!)
And it has nothing to do with mdx at all

2021-04-08 15:50 UTC, RomanDavlyatshin commented on src/theme/MDXPage/telegram.tsx
> +export const Telegram = () => (
This component name is unclear.
I suggest changing to `ContactUsViaTelegramBanner`

2021-04-08 15:50 UTC, RomanDavlyatshin commented on src/pages/installation.mdx
> +        <DockerIcon/>
Can't we make it easier a bit, just by providing a prop for the icon?
e.g. `<button class="button-ghost" iconSrc="../../static/img/external-link.svg">`

2021-04-08 17:03 UTC, IliaSolovev commented on src/pages/installation.mdx
> +        <DockerIcon/>
It is not a component. We decided to create css class instead component because so class can has `button` and `a`  tags

2021-04-09 07:31 UTC, IliaSolovev commented on src/pages/installation.mdx
> +        <DockerIcon/>
I created an Icon component and will use it here

2021-04-09 09:03 UTC, merged