EPMDJ-6738: Add additional information
Drill4J/drill4j.github.io pull request #3
Opened 2021-03-31 07:18 UTC by IliaSolovev

Issue: EPMDJ-6738

2021-03-31 11:40 UTC, RomanDavlyatshin requested changes

2021-03-31 11:40 UTC, RomanDavlyatshin commented on src/components/additional-information/styles.module.scss
> +  color: #687481;
@IliaSolovev  @RomanAchilov  can't we just introduce a `variables.scss` to avoid extra-work of replacing these values later?

2021-03-31 11:40 UTC, RomanDavlyatshin commented on src/components/additional-information/styles.module.scss
> +  text-align: left;
`text-align` is `left` by default, we can omit that, can't we?

2021-03-31 22:11 UTC, RomanAchilov approved these changes

2021-04-01 08:51 UTC, RomanDavlyatshin approved these changes

2021-04-01 15:20 UTC, merged