EPMDJ-6926: Update typography
Drill4J/drill4j.github.io pull request #30
Opened 2021-04-22 09:28 UTC by IliaSolovev

Issue: EPMDJ-6926

2021-04-23 06:37 UTC, IliaSolovev commented on src/css/_typography.scss
> +      margin-bottom: 3px;
I didn`t use flex here that align `svg` because we can have text in the link in two lines and with flex property it looked ugly

2021-04-23 06:59 UTC, RomanAchilov approved these changes

2021-04-23 07:51 UTC, RomanDavlyatshin requested changes

2021-04-23 07:51 UTC, RomanDavlyatshin commented on src/css/_typography.scss
> +    margin-top: 32px;
Now the `h2` in markdown is styled with two rules at the same time (the other one is at line `91`). The same goes for `h3` at line `112`. Isn't that kinda confusing? 🤔 
I suggest doing all of that in "one place":
```
.markdown {
  h1 {
  // all h1 rules here
  }
  h2 {
  // all h1 rules here
  }
  h3 { ...
}
```

2021-04-23 07:51 UTC, RomanDavlyatshin commented on src/css/_typography.scss
> +  & > h1 {
What's the reason behind using child combinator `>` for h1, but **not using** it for `h2` and `h3`?

2021-04-23 07:51 UTC, RomanDavlyatshin commented on src/css/_typography.scss
> +    &:first-of-type {
I guess this is for "the title" of the page, but It seems odd using it for `h2`. Can we discuss that?

2021-04-23 07:54 UTC, RomanDavlyatshin commented on src/css/_typography.scss
> +  & > h1 {
MFU: remove child combinator

2021-04-26 08:37 UTC, RomanDavlyatshin approved these changes
👍

2021-04-26 08:42 UTC, merged