EPMDJ-6928: add image viewer
Drill4J/drill4j.github.io pull request #31
Opened 2021-04-23 06:33 UTC by IliaSolovev

Issue: EPMDJ-6928

2021-04-23 07:00 UTC, RomanAchilov approved these changes

2021-04-26 08:32 UTC, RomanDavlyatshin requested changes
Looks great. Just one minor fix 👍😃

2021-04-26 08:32 UTC, RomanDavlyatshin commented on docs/usage-exapmle.mdx
> +import { Card, ImageViewer } from '../src/components';
I suggest changing name to `Image`, just to make it faster to type

2021-04-27 07:57 UTC, RomanDavlyatshin approved these changes

2021-04-27 08:12 UTC, merged