EPMDJ-6740: Add buttons classes
Drill4J/drill4j.github.io pull request #4
Opened 2021-03-31 07:19 UTC by IliaSolovev

Issue: EPMDJ-6740

2021-03-31 11:42 UTC, RomanDavlyatshin commented on src/css/button.scss
> +  @extend .button-primary;
❤️ 👍

2021-03-31 11:43 UTC, RomanDavlyatshin requested changes

2021-03-31 11:43 UTC, RomanDavlyatshin commented on src/pages/styles.module.scss
>  .heroBanner {
Why is it here 😮 ❓ @IliaSolovev

2021-03-31 22:09 UTC, RomanAchilov approved these changes

2021-04-01 08:40 UTC, RomanDavlyatshin requested changes

2021-04-01 08:40 UTC, RomanDavlyatshin commented on docs/usage-exapmle.md
> +    <img src="../static/img/download-icon.svg" alt=""/>
Please, do not use `<img>` tag for icons
I suggest implementing `<Icon src="../static/img/download-icon.svg">` component

2021-04-01 08:40 UTC, RomanDavlyatshin commented on docs/usage-exapmle.md
> +    <Download/>
Don't import `svg` icons into the page, as they will be indexed as part of the site content. (Use `<Icon>` component and display `svg` via `background-image` instead).

2021-04-01 10:19 UTC, merged