EPMDJ-6375: Add card
Drill4J/drill4j.github.io pull request #5
Opened 2021-03-31 07:19 UTC by IliaSolovev

Issue: EPMDJ-6375

2021-03-31 11:37 UTC, RomanDavlyatshin requested changes

2021-03-31 11:37 UTC, RomanDavlyatshin commented on src/components/card/card.tsx
> +    <img src={useBaseUrl(iconUrl)} alt={altTextForIcon} />
Do not use `<img>` tag for things that are not **_content_**
Consider implementing icons via any alternative tag (`<i>`, `<span>` ) and use `background-image` css property

2021-03-31 11:37 UTC, RomanDavlyatshin commented on src/components/card/card.tsx
> +  altTextForIcon: string;
That prop is not necessary (see comment on `<img>` usage bellow)

2021-03-31 11:37 UTC, RomanDavlyatshin commented on src/components/card/card.tsx
> +    <img
That should not be `<img>` as well

2021-03-31 22:08 UTC, RomanAchilov approved these changes

2021-04-01 08:47 UTC, RomanDavlyatshin commented on src/components/card/card.tsx
> +  children, iconUrl, href,
Rename `iconUrl` -> `iconSrc` (and use `src` everywhere).

2021-04-01 08:47 UTC, RomanDavlyatshin approved these changes

2021-04-01 15:18 UTC, merged