Update launch parameters
Drill4J/drill4j.github.io pull request #79
Opened 2021-11-10 08:23 UTC by Mazel-Tovr

add plugin id to autotest agent

2021-11-10 12:37 UTC, IliaSolovev approved these changes

2021-11-12 12:19 UTC, LikhanovMaxim requested changes

2021-11-12 12:19 UTC, LikhanovMaxim commented on docs/configuration/launch-parameters.mdx
> +| pluginId    | yes      | ""            | test2code         | the id of the plugin to which the auto test agent will send requests, you need to specify only if you use the command line to start the
create task : default value=test2code for command line
```suggestion
| pluginId    | yes      | test2code    |  | the id of the plugin to which the auto test agent will send requests |
```

2022-02-01 23:11 UTC, RomanAchilov requested changes
Nice branch and commit name, where task id?

2022-02-02 06:39 UTC, Mazel-Tovr commented
> Nice branch and commit name, where task id?

@RomanAchilov  look at commit name, there is a task id there. I don't see a problem that there is no task name in the name of the pr, because it is only on the GitHub site. It could be fixed in 2 clicks.
And yeah, I agree with u, the branch name is really cool.

2023-08-31 14:38 UTC, RomanDavlyatshin commented
obsolete

2023-08-31 14:38 UTC, closed without merging