EPMDJ-9391: Implement mermaidJs chart
Drill4J/drill4j.github.io pull request #84
Opened 2021-12-16 14:27 UTC by dmitrii-kliushentsev

2021-12-17 08:17 UTC, RomanDavlyatshin requested changes

2021-12-17 08:17 UTC, RomanDavlyatshin commented on docusaurus.config.js
> +          remarkPlugins: [require('mdx-mermaid')],
I don't think we need `mdx-mermaid` anymore. (We've got custom component, no reason to use ` ```mermaid... ` syntax).
I suggest to `npm uninstall` it :)

2021-12-17 08:17 UTC, RomanDavlyatshin commented on docs/diagrams/testing-diagrams.mdx
> +<MermaidComponent chart={`
Can we pass chart text as a child instead of prop, and then access it through `props.children`? 🤔 
```
<MermaidComponent>
// like that
{`
flowchart TD
  allSides
  ....
`}
//or even raw?
flowchart TD
  allSides
  ....
</MermaidComponent>
```

2021-12-17 08:17 UTC, RomanDavlyatshin commented on src/components/mermaid/index.ts
> +export { MermaidComponent } from './mermaid';
The "⛔" sign suggests a linting issue (no newline at the end of file).
Do you have eslint plugin installed?

2021-12-17 08:17 UTC, RomanDavlyatshin commented on src/components/mermaid/mermaid.tsx
> +};
Once again, check if eslint installed

2021-12-17 09:25 UTC, dmitrii-kliushentsev commented on docs/diagrams/testing-diagrams.mdx
> +<MermaidComponent chart={`
No, because throws a syntax error

2021-12-17 09:39 UTC, RomanDavlyatshin approved these changes
@IliaSolovev review, please 👁️ 
Note: pay attention to the `diagrams` directory. (Its contents do not match the contents of the respective section of the docs menu? But I might be wrong)

2022-02-01 23:07 UTC, RomanAchilov approved these changes

2025-02-10 10:17 UTC, closed without merging