EPMDJ-6744: Implement header
Drill4J/drill4j.github.io pull request #9
Opened 2021-04-01 13:04 UTC by RomanAchilov

2021-04-01 14:50 UTC, IliaSolovev requested changes

2021-04-01 14:50 UTC, IliaSolovev commented on src/css/custom.scss
> +.react-toggle {
Please, instead it paste `colorMode: {
      defaultMode: 'light',
      disableSwitch: true,
    },` in themeConfig

2021-04-01 17:38 UTC, RomanDavlyatshin requested changes

2021-04-01 17:38 UTC, RomanDavlyatshin commented on src/css/button.scss
> +  padding: 12px 48px !important;
What is the reasoning for the usage of `!important`?

2021-04-01 17:38 UTC, RomanDavlyatshin commented on src/css/overrides.scss
> +%media {
I got two issues with that 😢 :

## The naming

The placeholder name `%media` is very vague 😞 (it's unclear which properties it affects or what it does).
A more descriptive name could fix that (e.g. `%max-width-breakpoints` or `%media-max-width`)

## The overall idea
I've looked into tailwind docs and I've found all the necessary customization options:
1. That one allows breakpoints customization https://tailwindcss.com/docs/breakpoints
2. That one allows container size & padding customization https://tailwindcss.com/docs/container

TL;DR I suggest customizing containers behavior with `tailwind.config.js`

2021-04-05 06:54 UTC, IliaSolovev commented
As I understand you deleted `package-lock.json`. Pls return it

2021-04-05 06:59 UTC, IliaSolovev requested changes

2021-04-05 06:59 UTC, IliaSolovev commented on src/css/tailwind.css
> +@tailwind base;
Why you move it? And as I remember ww decide to remove base and components imports. Or you want to remove it in another PR?

2021-04-05 06:59 UTC, IliaSolovev commented on src/theme/Footer/index.tsx
> +        <section className="grid py-14 grid-cols-1 md:grid-cols-2 lg:grid-cols-footer" style={{ gap: '106px' }}>
Are you sure that there should be `106px`? And maybe update tailwindConfig for it?

2021-04-05 08:11 UTC, RomanDavlyatshin commented on src/css/_typography.scss
> +  min-width: 24px; // for social icons without text
Remove that pls 😄

2021-04-05 08:12 UTC, RomanDavlyatshin approved these changes

2021-04-05 08:58 UTC, IliaSolovev approved these changes

2021-04-05 08:59 UTC, merged